version: '3.8'

services:
  app:
    build: .
    container_name: todo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"
    command: /bin/sh -c "dockerize -wait tcp://db:3306 -timeout 60s php artisan migrate --seed && php-fpm"

  db:
    image: mysql:8
    container_name: todo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    networks:
      - app-network
    ports:
      - "3306:3306"

  queue:
    build: .
    container_name: todo-queue
    working_dir: /var/www
    command: /bin/sh -c "service cron start && supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    volumes:
      - .:/var/www
    depends_on:
      - app
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx/todo.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge
